[package]
name = "nova-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.8.2", features = [] }
portable-pty = "0.8"
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }
